name: Deploy on Railway

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
   steps:
      - uses: bervProject/railway-deploy@main
      with:
  railway_token: ${{ secret.RAILWAY_TOKEN }}
          env:
         HD_warp_id: ${{secrets.warp_id}}
